### PR TITLE
Add support for ocean fishing weather

### PR DESCRIPTION
**Pull request by quisquous**
This PR is meant to be applied on top of #147.  It adds a signature for the current weather (since you can't use predicted weather for ocean fishing) and limits the available ocean fish in the fish timer window by their weather restrictions.

f13db66b70fdbfdbae91861ae3d47db0b6d5f0ee and 763491297e85eb6667998d88e59208e2e0e90783 are the new commits here (sorry for two, I can squash if that makes it easier to read).

### CODE REVIEW

**Comment by Ottermandias** [comment]
I fetched the branch and looked over it, and had to do a bunch of changes, most notably removing your hardcoded enum stuff and instead use the sheets for it.
Since I wasn't sure how this all would work out, I did it myself instead of making review comments here, sorry if that comes off somehow rude, it is not intended that way.
I would appreciate if you'd look over my changes ([pr/n148_ocean_fishing_weather](https://github.com/Ottermandias/GatherBuddy/tree/pr/n148_ocean_fishing_weather)) since I won't do Ocean Fishing in the foreseeable future to test it - I think I verified that the sheet data results in the same values as the hardcoded stuff did, though.

**Comment by quisquous** [comment]
Looks good to me.  I also verified the uptime in the fish window, and gave it one test on an ocean fishing boat.  It all looks good.

I definitely understand the "there are too many changes for me to ask for, and I'm not even sure if it's possible, so maybe I'll rewrite it myself rather than ask somebody to do it speculatively when I'm not sure even how it'll all look".  It's not rude; I've been there a lot myself on code reviews.  Appreciate you taking the time to make this better.

Using game data is way better.  I didn't know that was there, or I would have used it.

(Was there something wrong with the previous sig, or is there some "unofficial" weather sig that I didn't know about?)

**Comment by Ottermandias** [comment]
Ghidra ordered the static fields there with multiple references, between the memory location you sigged and the one I sigged were a bunch of those references, which leads me to assume that there are separate structs/classes in that storage space.
Using the one with only one pointer offset directly from the data seemed more stable than using the one with offset by 400 bytes that would break whenever any of the (potential) structs between them would change size. (well, not the sig would break, but it would point to different data, you know what I mean :D )
I also tried to look into EnvironmentManager in ClientStructs etc. but that isn't mapped there, only its existence for the yaml :D

**Comment by quisquous** [comment]
Ah thanks, that makes a lot of sense.  I should learn how to use Ghidra and not just CheatEngine my way through everything.  Thanks for the explanation!

**Pull request merged**
